services:
  postgres:
    image: postgres:latest
    container_name: culinary-notes-postgres
    environment:
      POSTGRES_DB: culinary_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: